### PR TITLE
Changes in Mongo y AT files with groups annotation

### PR DESCRIPTION
**Pull request by alejandro2003**

### CODE REVIEW

**Comment by witokondoria** [comment]
:shipit:

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Pull request merged**
