### PR TITLE
[QA-130] coveralls integration

### PR DESCRIPTION
**Pull request by witokondoria**

### CODE REVIEW

**Comment by gbecares** [comment]
+1

**Comment by witokondoria** [comment]
Pending till trautonen/coveralls-maven-plugin/pull/97 gets approved, due:

Build error: Line number 575 is greater than the source file api/src/main/scala/com/stratio/decision/api/kafka/KafkaConsumer.scala size

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Decision/job/CD/825/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
As we have forked coveralls-maven-plugin, this error doesnt block us anymore :shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Decision/job/CD/831/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
