### PR TITLE
[DECISION-318] Change log path in log4j file

### PR DESCRIPTION
**Pull request by gbecares**

### CODE REVIEW

**Comment by imoreno-stratio** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Decision/job/CD/807/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Decision/job/CD/810/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Decision/job/CD/813/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
